### ISSUE TITLE
"system status" display not possible for several days?

### ISSUE THREAD

**Issue by dbloms** [michbeck100/pv-monitoring#11]
If I take a value greater than 1 day as the time period, then "No data in response" is always displayed in the "system status" graph.
As my inverter frequently goes into standby, I would like to see the history over several weeks.
Is that possible?
![image](https://github.com/michbeck100/pv-monitoring/assets/14087328/adc670b6-7b34-49a5-b1d1-377382083faa)

**Comment by michbeck100** [comment]
The values are aggregated for everything longer than 24 hours using retention policies and continuous queries (see https://github.com/michbeck100/pv-monitoring/blob/main/influxdb/influxdb-init.iql).
For strings it's not possible to aggregate the values with functions like `mean` or `max`. 
And it's not an option to keep the data forever in the original resolution of 10 seconds, that would be too much data.

If you have a solution for this, please reopen this issue.
