### ISSUE TITLE
No data at Grafana

### ISSUE THREAD

**Issue by maximilianbiebl** [michbeck100/pv-monitoring#12]
I set this up on my SynologyNas. With Grafana, I see some values, but most of the time I get the message "No data".

This is how my SunGather looks:

<html>
<body>
<h3>SunGather v0.5.2</h3><p></p><h4>Need Help?<span> </span><href a="https://github.com/bohdan-s/SunGather">https://github.com/bohdan-s/SunGather</href></h4><p></p><h4>NEW HomeAssistant Add-on:<span> </span><href a="https://github.com/bohdan-s/hassio-repository">https://github.com/bohdan-s/SunGather</href></h4><p></p>
Address
--

---- | device_type_code | SH8.ORT-V112
vr001 | run_state | ON
vr003 | last_reset | 2024-04-20 18:46:15
vr006 | daily_export_to_grid | 0.0 kWh
vr007 | daily_import_from_grid | 0.0 kWh
5001 | nominal_active_power | 8.0 kW
5002 | output_type | 3P4L
5003 | daily_power_yields | 18.4 kWh
5004 | total_power_yields | 17695 kWh
5008 | internal_temperature | 30.1 °C
5011 | mppt_1_voltage | 371.7 V
5012 | mppt_1_current | 1.1 A
5017 | total_dc_power | 776 W
5019 | phase_a_voltage | 234.7 V
5020 | phase_b_voltage | 234.0 V
5021 | phase_c_voltage | 236.8 V
5033 | total_reactive_power | -4 Var
5035 | power_factor | 1.0
5036 | grid_frequency | 50.0 Hz
5083 | meter_power | 0 W
5091 | load_power | 0 W
5113 | daily_running_time | 0 min
5006 | start_stop | Start
5007 | power_limitation_switch | Disable
5008 | power_limitation_setting | 100.0 %
5019 | power_factor_setting | 0.0
5036 | reactive_power_adjustment_mode | Off
5037 | reactive_power_percentage_setting | 0.0 %
5039 | power_limitation_adjustment | 0.0 kW
5040 | reactive_power_adjustment | 0.0 kVar
vr002 | timestamp | 2024-04-20 18:58:34
vr004 | export_to_grid | 0 W
vr005 | import_from_grid | 0 W

Total 33 registers

Configuration	Value
host	192.168.188.116
port	8082
timeout	5
retries	3
RetryOnEmpty	False
model	SH8.ORT-V112
serial_number	A232280213
level	2
scan_interval	10
use_local_time	True
smart_meter	True
connection	http
slave	1
start_time	

And this is the Inverter Config:

inverter:
  host: "IP.Adress"                      # [Required] IP Address of the Inverter or Dongle
  port: 8082                               # [Optional] Default for modbus is 502, for http is 8082
  timeout: 5                              # [Optional] Default is 10, how long to wait for a connection
  retries: 3                              # [Optional] Default is 3, how many times to retry if connection fails
  slave: 0x01                             # [Optional] Default is 0x01
  scan_interval: 10                       # [Optional] Default is 30
  connection: http                      # [Required] options: modbus, sungrow, http
  model: "SH8.ORT-V112"     

I don't have any error messages in any of the docker images.

That's part of my dashboard. It doesn't show everything, but it illustrates the problem.

![image](https://github.com/michbeck100/pv-monitoring/assets/72378450/77b65cfa-7178-43c8-8059-4ef9ef41534d)

Thanks for the Project and your Help.
Maximilian

**Comment by michbeck100** [comment]
Not sure if the http endpoint is the problem. I think that it doesn’t expose so many values like the modbus endpoint. Please try to use the port 502 of the inverter. For help please also check the sungather documentation.

**Comment by maximilianbiebl** [comment]
With http and port 502 i don't get any values in SunGather. 
First I tried it modbus and  had the same problem with not so many values. But like in  #3 i had the out of range error so I tried http.

**Comment by maximilianbiebl** [comment]
Changing the Level to 3 did the thing.

inverter:
  host: IP.Adress                      # [Required] IP Address of the Inverter or Dongle
  port: 502                               # [Optional] Default for modbus is 502, for http is 8082
  timeout: 5                              # [Optional] Default is 10, how long to wait for a connection
  retries: 3                              # [Optional] Default is 3, how many times to retry if connection fails
  slave: 0x01                             # [Optional] Default is 0x01
  scan_interval: 10                       # [Optional] Default is 30
  connection: modbus                      # [Required] options: modbus, sungrow, http
  model: "SH8.ORT-V112"                         # [Optional] This is autodetected on startup, only needed if detection issues or for testing
                                            # See model list here: https://github.com/bohdan-s/SunGather#supported
  smart_meter: True                       # [Optional] Default is False, Set to true if inverter supports reading grind / house consumption
  use_local_time: True                    
  **level: 3**
