### ISSUE TITLE
Modbus import/export charge/discharge always negative

### ISSUE THREAD

**Issue by dmindfuse** [michbeck100/pv-monitoring#14]
Hi @michbeck100. I'm reading my SH8.0RT using the modbus proxy implementation following I completely destroyed and redeployed from scratch the entire project this week to get everything up to date. I get readings, but charge/discharge battery are both always negative at the same time.

At the webserver I observe that state_battery_charging and state_battery_discharging are always both -1 at the same time (currently while the battery is charging). I suspect this is the root of the problem, maybe they refer to the same register? Where or how do I fix this? 

![image](https://github.com/michbeck100/pv-monitoring/assets/59705562/505886a6-6746-43b3-ad3d-06bfcacc2aaf)

Appreciate a pointer.
Thanks

**Comment by michbeck100** [comment]
no idea why this happens. Please raise an issue on the sungather project: https://github.com/bohdan-s/SunGather/issues
