### ISSUE TITLE
Graphen mit Gruppierung

### ISSUE THREAD

**Issue by Josuruma** [michbeck100/pv-monitoring#6]
Moin,
irgendwie werden die Graphen mit Gruppierung nicht korrekt dargestellt.
Bei einem Tag wird nur irgendwas im Bereich von 00:00 bis 04:00 Uhr angezeigt.
Bei einer Woche oder mehr nichts mehr.
![2023-07-03 13_45_24-Grafana - Brave](https://github.com/michbeck100/pv-monitoring/assets/35657189/602bf8be-2738-422b-ae73-cf13ea549f23)
![2023-07-03 13_49_17-Grafana - Brave](https://github.com/michbeck100/pv-monitoring/assets/35657189/0925b4d9-4e96-4a2e-9b5a-8136e7ca22f2)
Eine Idee woran das liegt?

**Comment by michbeck100** [comment]
Das Verhalten ist normal. Die Query dahinter nutzt eine `GROUP BY` Abfrage. Und wenn man den Gruppierungszeitraum auf `1w` stellt, aber die Time Range auf zb. `Last 24 hours` steht, dann passt das nicht zusammen. Der Gruppierungszeitraum muss dann auch zur Time Range passen. Also bei `1w` sollte mindestens auch die Time Range größer als 1 Woche sein. 

Die Zeitleiste auf der X Achse ist dabei leider etwas verwirrend. Davon bitte nicht ablenken lassen. Die Ansicht muss man eher so verstehen: "Die letzten 7 Tage wurden pro Tag x kWh produziert." oder "im letzten Jahr wurden pro 30d X kWh produziert"

**Comment by Josuruma** [comment]
Ah, dann hatte ich das missverstanden, vielen Dank!
