### ISSUE TITLE
Speicher SoC

### ISSUE THREAD

**Issue by Knock82** [michbeck100/pv-monitoring#9]
Wähle ich als Timerange mehr als die letzten 24h aus verschwindet der Detailgraph Speicher-SoC.

**Comment by Knock82** [comment]
Ändere ich 

SELECT mean(battery_level) * mean(max_soc) / 100 FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(none)

zu

SELECT mean(battery_level) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(none)

schaut es gut aus. Verstehe diese Berechnung aber auch nicht.

**Comment by michbeck100** [comment]
Hast Recht. Hab ich entfernt.
